include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

gemnasium-dependency_scanning:
  variables:
    DS_REMEDIATE: "false"

stages:
  - test
  - composer
  - qa

image: in2code/php:8.2-fpm

composer:
  stage: composer
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /tmp/composer/cache
  script: composer install
  artifacts:
    paths:
      - vendor/

qa-composer:
  stage: qa
  script: composer run qa-composer
  only:
    changes:
      - "composer.json"

qa-lint:
  stage: qa
  script: composer run qa-lint
  only:
    changes:
      - "**/*.php"

qa-phpcs:
  stage: qa
  script: composer run qa-phpcs
  only:
    changes:
      - "**/*.php"

qa-phpmd:
  stage: qa
  script: composer run qa-phpmd
  only:
    changes:
      - "**/*.php"

qa-phpstan:
  stage: qa
  script: composer run qa-phpstan
  only:
    changes:
      - "**/*.php"

qa-psalm:
  stage: qa
  script: composer run qa-psalm
  only:
    changes:
      - "**/*.php"

qa-phpunit-coverage:
  image: in2code/php-dev:8.2-fpm
  stage: qa
  script: XDEBUG_MODE=coverage vendor/bin/phpunit -c .phpunit.xml --coverage-text --colors=never
  only:
    changes:
      - "**/*.php"
  artifacts:
    reports:
      junit: .project/artifacts/rspec.xml
  coverage: '/Lines:\s+\d+\.\d+/'

qa-infection:
  image: in2code/php-dev:8.2-fpm
  stage: qa
  script: XDEBUG_MODE=coverage vendor/bin/infection --configuration=.infection.json -j$(nproc) --min-covered-msi=100 --min-msi=100
  only:
    changes:
      - "**/*.php"
  artifacts:
    reports:
      junit: .project/artifacts/rspec.xml
