version: "3.7"

services:
  php:
    build:
      context: .project/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/app/:cached
      - $HOME/.composer/auth.json:/tmp/composer/auth.json
      - $HOME/.composer/cache/:/tmp/composer/cache/

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_PORT: 8025
